2010-09-21 13:11:15,455 indico.requestHandler - ERROR base.py:324

Request 174337844 failed: "TemplateExecException: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 26: ordinal not in range(128) - - - -> {Python code generated from templates is available in /opt/indico/tmp/EventLocationInfo.tpl.error.py, /opt/indico/tmp/ConferenceDataModification.py file(s)}"

url: http://www.lsw.uni-heidelberg.de/indico/conferenceModification.py/data?confId=2

parameters: {'confId': '2'}

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/cds_indico-0.97_rc1-py2.5.egg/MaKaC/webinterface/rh/base.py", line 475, in process
    res = self._process()
  File "/usr/lib/python2.5/site-packages/cds_indico-0.97_rc1-py2.5.egg/MaKaC/webinterface/rh/conferenceModif.py", line 108, in _process
    return self._displayDefaultPage()
  File "/usr/lib/python2.5/site-packages/cds_indico-0.97_rc1-py2.5.egg/MaKaC/webinterface/rh/conferenceModif.py", line 320, in _displayDefaultPage
    return p.display(**pars)
  File "/usr/lib/python2.5/site-packages/cds_indico-0.97_rc1-py2.5.egg/MaKaC/webinterface/pages/base.py", line 165, in display
    self._display( params ), \
  File "/usr/lib/python2.5/site-packages/cds_indico-0.97_rc1-py2.5.egg/MaKaC/webinterface/pages/main.py", line 159, in _display
    body = WMainBase(self._getBody( params ), self._timezone, self._getNavigationDrawer(),
  File "/usr/lib/python2.5/site-packages/cds_indico-0.97_rc1-py2.5.egg/MaKaC/webinterface/pages/conferences.py", line 2217, in _getBody
    return self._applyFrame( self._getPageContent( params ) )
  File "/usr/lib/python2.5/site-packages/cds_indico-0.97_rc1-py2.5.egg/MaKaC/webinterface/pages/conferences.py", line 3037, in _getPageContent
    return p.getHTML( pars )
  File "/usr/lib/python2.5/site-packages/cds_indico-0.97_rc1-py2.5.egg/MaKaC/webinterface/wcomponents.py", line 193, in getHTML
    tempHTML = TemplateExec.executeTemplate( text, vars, self.tplId )
  File "/usr/lib/python2.5/site-packages/cds_indico-0.97_rc1-py2.5.egg/MaKaC/common/TemplateExec.py", line 406, in executeTemplate
    raise TemplateExecException( e )
TemplateExecException: TemplateExecException: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 26: ordinal not in range(128) - - - -> {Python code generated from templates is available in /opt/indico/tmp/EventLocationInfo.tpl.error.py, /opt/indico/tmp/ConferenceDataModification.py file(s)}

